#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=keeweb

# Retrieve arguments
	domain=$1
	path=$2
	dropbox=$3
	is_public=$4

# Save app settings
	sudo yunohost app setting $app dropbox -v "$dropbox"
	sudo yunohost app setting $app is_public -v "$is_public"

# Check domain/path availability
	sudo yunohost app checkurl $domain$path -a $app \
		|| (echo "Path not available: $domain$path" && exit 1)

# If a Dropbox app key is present, add it
	if [ -n "$dropbox" ];
	then
		sudo sed -i.bak s/qp7ctun6qt5n9d6/$dropbox/g ../sources/index.html
	fi
		
# Copy source files
	final_path=/var/www/$app
	sudo mkdir -p $final_path
	sudo cp -a ../sources/. $final_path

# Set permissions to app files
	sudo chown -R root:root $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
	sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
	sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is public, add url to SSOWat conf as skipped_uris
	if [ "$is_public" = "Yes" ];
	then
	  # unprotected_uris allows SSO credentials to be passed anyway.
	  sudo yunohost app setting $app unprotected_uris -v "/"
	fi

# Restart services
	sudo service nginx reload
	sudo yunohost app ssowatconf
