#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
	source /usr/share/yunohost/helpers

# Retrieve old app settings
	domain=$(ynh_app_setting_get "$app" domain)
	path=$(ynh_app_setting_get "$app" path)

# Restore NGINX configuration
	conf=/etc/nginx/conf.d/$domain.d/$app.conf
	if [ -f $conf ]; then
		ynh_die "There is already a nginx conf file at this path: $conf"
	fi
	sudo cp -a ./nginx.conf $conf	

# Restore sources & data
	src_path="/var/www/${app}"
	sudo cp -a ./sources "$src_path"

# Restore permissions to app files
	sudo chown -R root: "$src_path"

# Restart webserver
	sudo service nginx reload
