#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# INSTALL SOURCES
#=================================================

ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
mkdir -p "$install_dir"
cp -r ../sources/extra_files/* "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================

ynh_config_add_nginx

#=================================================
# USE THE CONFIG FILE
#=================================================

ynh_replace --match="(no-config)" --replace="config.json" --file="$install_dir/index.html"

#=================================================
# COPY THE CONFIG FILE
#=================================================

# Copie ou modification d'un fichier de config
ynh_config_add --template="config.json" --destination="$install_dir/config.json"

#=================================================
# SECURING FILES AND DIRECTORIES
#=================================================

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
